/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gargsgarage;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    //placeholder for now
    @Test
    public void alwaysTrue(){
        assertTrue(true);
    }
}
