/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)

    //postgresql dependecy
    implementation("org.postgresql:postgresql:42.7.3")

    //JBCrypt dependency
    implementation("org.mindrot:jbcrypt:0.4")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.gargsgarage.todos.TODOServer")
}

// Configure the Shadow JAR task
tasks.shadowJar {
    archiveBaseName.set("todoserver")
    archiveClassifier.set("")
    archiveVersion.set("1.0")
}

tasks.build {
    dependsOn(tasks.shadowJar)
}
